### ISSUE TITLE
Hover problem on BGS group page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#193]
If you hover over the news story 'consultation on the regulation of medical associate professions in the UK' on http://bgs-dev.mrmdev.co.uk/peri-operative-care-of-older-people-undergoing-surgery-pops it starts flashing like crazy! I'm using Chrome. I can show you on screen share if that helps.

**Comment by dilwarhussain** [comment]
@angievanhegan @StephMSlack This has been fixed. We've had to make a small change to avoid this happening again with the summaries on cards. If the 'Equal heights' checkbox is not checked for feeds, the summaries will not show, they will work as any other card with no summary text. We think that 'Equal heights' will be used more often than not as the cards looks much nicer when they are all the same height so we don't expect this to be a big deal. 

Please do test this out on this page: 
http://bgs-dev.mrmdev.co.uk/peri-operative-care-of-older-people-undergoing-surgery-pops
If you change the settings on the feeds in the 'Additional content' section and let us know if you're happy with how this is working now.

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain 
does the resource feed work differently? Currently the equal heights box is not ticked, but you can still see the card content. The feed isn't fluttering anymore which is the main thing.

If the equal heights box always needs to be ticked to ensure the feed works correctly, can it be ticked by default?

**Comment by dilwarhussain** [comment]
@StephMSlack Yes the Resources/Blog/Policy & Media pages are different as they are custom built for those specific pages, they all have equal/specific heights set up for the cards.

When displaying feeds of content around the site you have the option to use equal heights. Disabling equals heights will come in handy if you decide to display some content with 1 item per row, that way you won't get some cards appearing much larger than others because the cards would be forced to all be equal height.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
